### PR TITLE
Charging Schematic Updates

### PR DESCRIPTION
**Pull request by Cameron-Gordon**
Added Shielding, added fuses, rearanged F1, removed 2 pin connector.

### CODE REVIEW

**Review by mccauleyma — CHANGES_REQUESTED** [review]
- Fusing the neutral line? (Im not hard vetoing, but I need justification why)
- No, the TS shielding does not work like that. The TS chassis actually has shield grounding built in so there is no wire like that necessary

**Comment by mccauleyma** [comment]
Oh, and I assume you're working on it already, but just in case: yes, the end goal is to have all those fuses actually indicated with their ratings (plz).

**Review by mccauleyma — APPROVED** [review]
Good. Thanks for those fixes.
As a note, you (or Peter maybe?) will still need to figure a way to ground the shield on the charger side of the TS lines.

**Review by gardnerdy — APPROVED** [review]

**Review by mccauleyma — CHANGES_REQUESTED** [review]
Idk what the heck you did, but the voltage tap board is full of conflicts rn. Those need to be fixed

**Review by gardnerdy — APPROVED** [review]

**Comment by gardnerdy** [comment]
Fuse annotations on Therm board got shifted. go ahead and keep cams version

**Comment by mccauleyma** [comment]
I saw that, but are we ok with that?

**Review by mccauleyma — APPROVED** [review]

**Pull request merged**
