### PR TITLE
integrated matts Battery BOx updates

### PR DESCRIPTION
**Pull request by gardnerdy**
added MC air control lines
Moved tsal to after imd fuse

### CODE REVIEW

**Comment by gardnerdy** [comment]
@mccauleyma I'm not sure what the conflictions are because i swear i was working from the latest pull after your last branch (MC integration) was merged . Please review and make sure i didnt mess anything up. looks like it was just wires getting moved around causing the conflict.

**Review by mccauleyma — APPROVED** [review]

**Review by mccauleyma — APPROVED** [review]
Looks fine to me. Is there an easier way to just override and resolve using your file for everything.
Not sure why but it is confused and says you swapped like all the precharge vs AIR stuff.

**Comment by gardnerdy** [comment]
@mccauleyma i did swap them, you had them backwards lol

**Comment by mccauleyma** [comment]
👀. Yikes lol

**Pull request merged**
