### PR TITLE
Added BMS Control Board 

### PR DESCRIPTION
**Pull request by ziptol**
Added folder with BMS control board schematic to the master schematic folder.

### CODE REVIEW

**Review by mccauleyma — CHANGES_REQUESTED** [review]
Looks great
- Did you intend to create a PCB file too?
- Need to switch paper size to A (we use ANSI not ISO)
- Careful in the comment of the title block. You need to keep the bottom two lines empty for that general attribution and GitHub link we do now

**Review by mccauleyma — APPROVED** [review]
Looks good!

**Review by mccauleyma — APPROVED** [review]
Great work! Thank you for making all those changes.

Does this still need the ideal diode chip and mosfet to be added? Or is the plan to just represent it as a diode in this?

**Review by gardnerdy — COMMENTED** [review]
Waiting to review pending the replacement of the relays with ideal diodes. Zach and I still working out the kinks in how to apply it to the other relays since their operation is different. cant really use the ideal diode to replace the other relays in the way we were originally thinking but we are still going down the semiconductor route

**Review by gardnerdy — APPROVED** [review]

**Pull request merged**
